define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = {
        male: ["John", "Lucas", "Jay", "Cael", "Jordon", "Slade", "James", "Richard", "Adam", "Bob", "David", "Frank", "Hugh", "Isaias", "Jaron", "Joseph", "Lawrence", "William", "Byrle", "Brand", "Huey", "Everett", "Gare", "Goran", "Henderson", "Garner", "Farly", "Mendie", "Caryl", "Herman", "Ricardo", "Archibold", "Gorden", "Marshal", "Sylas", "Adolphe", "Riobard", "Ingra", "Foss", "Kimble", "Thaddus", "Bart", "Paxon", "Hunter", "Juan", "Zacharias", "Ferris", "Franky", "Eugenius", "Fabien", "Al", "Buck", "Drugi", "Freemon", "Austen", "Dale", "Trueman", "Ernie", "Ikey", "Base", "Waverley", "Frazer", "Ferrel", "Curt", "Curcio", "Rolland", "Godfrey", "Ruy"],
        female: ["Eve", "Lily", "Eliza", "Athene", "Megan", "Janice", "Tiffany", "Shannon", "Abbey", "Abigail", "Jiang", "Lei", "Shan", "Qiu", "Andrea", "Dawn", "Laura", "Patricia", "Rhonda", "Robin", "Nadeen", "Katha", "Hilda", "Marcile", "Tootsie", "Marcelle", "Rosetta", "Chantalle", "Rochelle", "Gerhardine", "Codie", "Vanda", "Eilis", "Dollie", "Felisha", "Sindee", "Tamarra", "Giuditta", "Patti", "Joya", "Petronilla", "Hinda", "Cindy", "Micky", "Evelyn", "Dalia", "Kristyn", "Maggy", "Gwennie", "Irita", "Harmonia", "Kaila", "Lurette", "Ashlie", "Venita", "Merla", "Corri", "Rafaelita", "Elaina", "Essa", "Emogene", "Norean", "Anastassia", "Patrizia", "Margarette", "Michaela", "Essy", "Elinore", "Layne", "Dynah", "Tim", "Lorelei", "Timmie", "Bertine", "Codee", "Sarah", "Martie", "Norean", "Dedra", "Micki", "Clementine", "Elizabet", "Nicolette", "Jacintha", "Editha", "Lyndell", "Susana", "Cinnamon", "Dinah", "Emyle", "Nata", "Blythe", "Hope", "Penelopa", "Sydel", "Koralle", "Revkah", "Sandie", "Casey", "Ester", "Tessa", "Aurelia", "Pammie", "Catherina", "Toinette", "Berti", "Agathe", "Carmita", "Drucy", "Kelly", "Nessy", "Lindy", "Glad", "Kordula", "Dode", "Celestine", "Consuelo", "Gayle", "Loreen", "Ailsun"],
        surname: ["Jones", "Millions", "Shears", "Genner", "Fraine", "Genman", "Harman", "Gray", "Layne", "Kincaid", "Knoz", "Marshall", "Mabbs", "Orlebar", "Otway", "Pennyvice", "Stallman", "Sharples", "Taylor", "Underwood", "Tye", "Ling", "Becker", "Deckard", "Wild", "Screwmoore", "Jensen", "Margoulis", "Page", "Cassan", "Malik", "Pritchard", "Darrow", "Brussels", "Thomann", "Sposito", "Catterall", "Lovelady", "Oppie", "Johnikin", "Pretswell", "Clementel", "Solomon", "Duke", "Ivakhnov", "Crickmer", "Hughlock", "Duckerin", "Brader", "Audas", "Alliot", "Bice", "Cuell", "Cisar", "Beaglehole", "Grannell", "Betho", "Dobrovsky", "Jakubowicz", "Gentzsch", "Koenen", "Adolfsen", "Forte", "Moreing", "Bonnin", "Briggs", "Count", "Leggat", "Castanaga", "Overill", "Walkley", "Chiswell", "Grizard", "Halbert", "Porte", "Brentnall", "Housecraft", "Shepcutt", "Sergeant", "Gunby", "Beiderbecke", "Jenicek", "Tuffley", "Hinrich", "Pace", "Elflain", "McCay", "Insko", "Burgiss", "Videneev", "Pietruszka", "Greenhalf", "Dawid", "Toffel", "Bratley", "Janney", "Sotworth", "Toomer", "O'Mahoney", "Meachem", "Ashbe", "Tilt", "Pearcy", "Bortolussi", "Maypole", "Stopford", "Healeas", "Rockwell", "Blackall", "Tugman", "Turmall", "Cannop", "Syde", "Dymoke", "Mattaser", "Havesides", "Dodds", "Argente", "Berni", "Kanter", "Checkley", "Gianasi", "Gatherer", "Warrener", "Alpine", "Senyard", "Hardingham", "Pallis", "Flaverty", "Graeser", "Shields", "Lawlan", "Capon"]
    };
});
