export default {
    C13: {
        type: "Pistol",
        name: "BudgetArms C-13",
        brand: "BudgetArms",
        desc: "A light duty autopistol used as a hold-out and lady 's gun",
        ammo: "5mm",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 1,
        crit: 1.1,
        diceThrows: 1,
        shots: 8,
        rateOfFire: 2,
        cost: 75,
        range: 50,
    },
    cybermag: {
        type: "Pistol",
        brand: "Dai Lung",
        name: "Cybermag 15",
        desc: "Cheap Hong Kong knockoff, often used by boosters and other street trash.",
        ammo: "6mm",
        reliability: 1,
        accuracy: 40,
        rarity: 2,
        damage: 1,
        crit: 3.1,
        diceThrows: 1,
        shots: 8,
        rateOfFire: 2,
        cost: 75,
        range: 50,
    },
    X22: {
        type: "Pistol",
        brand: "Federated Arms",
        name: "X-22",
        desc: 'The ubiquitous "Polymer-one-shot" cheap plastic pistol. Available in designer colors.',
        ammo: "6mm",
        reliability: 1,
        accuracy: 50,
        rarity: 2,
        damage: 1,
        crit: 3.7,
        diceThrows: 1,
        shots: 8,
        rateOfFire: 2,
        cost: 150,
        range: 50,
    },
    avenger: {
        type: "Pistol",
        brand: "Militech",
        name: "Arms Avenger",
        desc: "A well-made autopistol with good range and accuracy. A professional's gun.",
        ammo: "9mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 1,
        crit: 22,
        diceThrows: 2,
        shots: 10,
        rateOfFire: 2,
        cost: 250,
        range: 50,
    },
    streetM: {
        type: "Pistol",
        brand: "Dai Lung",
        name: "Streetmaster",
        desc: "Another Dai Lung cheapie, build for the Street.",
        ammo: "10mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 3,
        crit: 24,
        diceThrows: 2,
        shots: 12,
        rateOfFire: 2,
        cost: 250,
        range: 50,
    },
    X9M: {
        type: "Pistol",
        brand: "Federated Arms",
        name: "X-9m",
        desc: "A sturdy Solo's gun, used as a standard military sidearm in the U.S. and E.C.C.",
        ammo: "9mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 1,
        crit: 4,
        diceThrows: 2,
        shots: 12,
        rateOfFire: 2,
        cost: 300,
        range: 50,
    },
    auto3: {
        type: "Pistol",
        brand: "BudgetArms",
        name: "Auto 3",
        desc: "It's cheap. It's powerful. It blows up sometimes. What else do you want?",
        ammo: "11mm",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 0,
        crit: 6.5,
        diceThrows: 3,
        shots: 8,
        rateOfFire: 2,
        cost: 350,
        range: 50,
    },
    type35: {
        type: "Pistol",
        brand: "Sternmeyer",
        name: "Type 35",
        desc: "Rugged, reliable, with excellent stopping power. Another fine E.C.C. product from the United Germanies.",
        ammo: "11mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 0,
        crit: 7,
        diceThrows: 3,
        shots: 8,
        rateOfFire: 2,
        cost: 400,
        range: 50,
    },
    armalite44: {
        type: "Pistol",
        brand: "Armalite",
        name: "Armalite 44",
        desc: "Designed as an alternate to the 1998 U.S. Army sidearm trials. A solid contender.",
        ammo: "12mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 1,
        crit: 34,
        diceThrows: 4,
        shots: 8,
        rateOfFire: 1,
        cost: 450,
        range: 50,
    },
    colt: {
        type: "Pistol",
        brand: "Colt",
        name: "AMT Model 2000",
        desc:
            "Now the standard officer's sidearm for the U.S. Army, the M-2000 served well in the Central American Wars.",
        ammo: "12mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 1,
        crit: 6.1,
        diceThrows: 4,
        shots: 8,
        rateOfFire: 1,
        cost: 75,
        range: 50,
    },
    miniauto: {
        type: "Submachine Gun",
        brand: "Uzi",
        name: "Miniauto 9",
        desc:
            "Uzi's entry into the 21st century, all plastic, with rotary electric clip and adjustable trigger. The choice for many security solos.",
        ammo: "9mm",
        reliability: 1,
        accuracy: 60,
        rarity: 1,
        damage: 1,
        crit: 1.2,
        diceThrows: 2,
        shots: 30,
        rateOfFire: 35,
        cost: 475,
        range: 150,
    },
    MP2013: {
        type: "Submachine Gun",
        brand: "Heckler & Koch",
        name: "H&K MP-2013",
        desc: "Heckler & Koch's updating of the MP-5K classic, with compud plastics and build in silencing.",
        ammo: "10mm",
        reliability: 1,
        accuracy: 60,
        rarity: 1,
        damage: 3,
        crit: 12,
        diceThrows: 2,
        shots: 35,
        rateOfFire: 32,
        cost: 450,
        range: 150,
    },
    assault2: {
        type: "Submachine Gun",
        brand: "Federated Arms",
        name: "Tech Assault II",
        desc:
            "An updated version of the venerable Tech Assault I, features larger clip, better autofire, no melting. Honest.",
        ammo: "6mm",
        reliability: 1,
        accuracy: 60,
        rarity: 1,
        damage: 1,
        crit: 5,
        diceThrows: 1,
        shots: 50,
        rateOfFire: 25,
        cost: 400,
        range: 150,
    },
    minami10: {
        type: "Submachine Gun",
        brand: "Arasaka",
        name: "Minami 10",
        desc: "The standard Arasaka Security weapon, found worldwide. A good, all around weapon.",
        ammo: "10mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 3,
        crit: 21,
        diceThrows: 2,
        shots: 40,
        rateOfFire: 20,
        cost: 500,
        range: 200,
    },
    MPK9: {
        type: "Submachine Gun",
        brand: "Heckler & Koch",
        name: "H&K MPK-9",
        desc: "A light composite Submachine gun with integral sights. Used by many Euro solos.",
        ammo: "9mm",
        reliability: 1,
        accuracy: 60,
        rarity: 1,
        damage: 3,
        crit: 15,
        diceThrows: 2,
        shots: 35,
        rateOfFire: 25,
        cost: 520,
        range: 200,
    },
    MPK11: {
        type: "Submachine Gun",
        brand: "Heckler & Koch",
        name: "MPK-11",
        desc:
            "Possibly the most used Solo's gun in existence, the MPK-11 can be modified into four different designs, including a bullpup configuration, standard SMG, an assault carbine and a grenade launcher mount.",
        ammo: "9mm",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 1,
        crit: 3,
        diceThrows: 4,
        shots: 30,
        rateOfFire: 20,
        cost: 700,
        range: 200,
    },
    SMG21: {
        type: "Submachine Gun",
        brand: "Sternmeyer",
        name: "SMG-21",
        desc: "Sternmeyer's best entry in the anti-terrorist category, with wide use on C-SWAT teams and PsychoSquads.",
        ammo: "12mm",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 0,
        crit: 5,
        diceThrows: 3,
        shots: 30,
        rateOfFire: 15,
        cost: 500,
        range: 200,
    },
    MAC14: {
        type: "Assault Rifle",
        brand: "Ingram",
        name: "MAC-14",
        desc: "Updated MAC-10, with composite body and cylindrical feeding magazine.",
        ammo: "12mm",
        reliability: 1,
        accuracy: 30,
        rarity: 1,
        damage: 1,
        crit: 5,
        diceThrows: 4,
        shots: 20,
        rateOfFire: 10,
        cost: 650,
        range: 200,
    },
    roninL: {
        type: "Assault Rifle",
        brand: "Militech",
        name: "Ronin Light Assault",
        desc: "A light, all purpose update, similar to the M-16B.",
        ammo: "5.56",
        reliability: 1,
        accuracy: 60,
        rarity: 1,
        damage: 0,
        crit: 4,
        diceThrows: 5,
        shots: 35,
        rateOfFire: 30,
        cost: 450,
        range: 400,
    },
    AKR20: {
        type: "Assault Rifle",
        brand: "Kalashnikov",
        name: "AKR-20",
        desc: "A plastic and carbon fiber update of the AKM, distributed throughout the remains of the Soviet bloc.",
        ammo: "5.56",
        reliability: 1,
        accuracy: 50,
        rarity: 1,
        damage: 0,
        crit: 4,
        diceThrows: 5,
        shots: 30,
        rateOfFire: 30,
        cost: 500,
        range: 400,
    },
    FNRAL: {
        type: "Assault Rifle",
        brand: "FN",
        name: "FN-RAL",
        desc: "The standard NATO assault weapon for battlefield work. Bullpup design, collapsing stock.",
        ammo: "7.62",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 2,
        crit: 4,
        diceThrows: 6,
        shots: 35,
        rateOfFire: 30,
        cost: 600,
        range: 400,
    },
    A80: {
        type: "Assault Rifle",
        brand: "Kalashnikov",
        name: "A-80",
        desc: "Another Soviet retread, with improved sighting and lightened with composites.",
        ammo: "7.62",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 2,
        crit: 4,
        diceThrows: 6,
        shots: 35,
        rateOfFire: 25,
        cost: 550,
        range: 400,
    },
    RA12: {
        type: "Shotgun",
        brand: "Arasaka",
        name: "Arasaka Rapid Assault 12",
        desc:
            "A high powered auto-shotgun with lethal firepower. Used by Arasaka worldwide. Another good reason to avoid the Boys in Black.",
        ammo: "12 gauge",
        reliability: 1,
        accuracy: 40,
        rarity: 1,
        damage: 0,
        crit: 4,
        diceThrows: 4,
        shots: 20,
        rateOfFire: 2,
        cost: 900,
        range: 50,
    },
    stakeout: {
        type: "Shotgun",
        brand: "Sternmeyer",
        name: "Stakeout 10",
        desc: "Light duty stakeout shotgun, used by city police departments.",
        ammo: "12 gauge",
        reliability: 1,
        accuracy: 30,
        rarity: 1,
        damage: 0,
        crit: 4,
        diceThrows: 4,
        shots: 10,
        rateOfFire: 2,
        cost: 450,
        range: 50,
    },
    club: {
        type: "Melee",
        brand: "Makeshift",
        name: "Club",
        desc: "Made from scraps of a makeshift house, this club has been proved to be great in close combat.",
        ammo: "",
        reliability: 1,
        accuracy: 50,
        rarity: 2,
        damage: 0,
        crit: 4,
        diceThrows: 1,
        shots: 1,
        rateOfFire: 1,
        cost: 0,
        range: 2,
    },
    spoon: {
        type: "Melee",
        brand: "Makeshift",
        name: "Spoon",
        desc: "So many eyes have been gouged out with this.",
        ammo: "",
        reliability: 1,
        accuracy: 100,
        rarity: 2,
        damage: 50,
        crit: 50,
        diceThrows: 1,
        shots: 1,
        rateOfFire: 1,
        cost: 0,
        range: 2,
    },
    fists: {
        type: "Melee",
        brand: "Unequipped",
        name: "Fists",
        desc: "Ready to beat the shit out of the enemies of yours? Of course you are, you were made ready for it.",
        ammo: "",
        reliability: 1,
        accuracy: 100,
        rarity: 1,
        damage: 5000,
        crit: 10,
        diceThrows: 1,
        shots: 1,
        rateOfFire: 1,
        cost: 0,
        range: 2,
    },
};
