export default {
    vehicles: [
        {
            name: "Scooter",
            price: 500,
            health: 100,
            maxSpeed: 50,
            driver: null,
            passengers: null,
        },
        {
            name: "Motorcycle",
            price: 1500,
            health: 200,
            maxSpeed: 150,
            driver: null,
            passengers: null,
        },
        {
            name: "CityCar",
            price: 2e3,
            health: 400,
            maxSpeed: 180,
            driver: null,
            passengers: null,
        },
        {
            name: "Small Subcompact",
            price: 6e3,
            health: 500,
            maxSpeed: 160,
            driver: null,
            passengers: null,
        },
        {
            name: "Medium Sedan",
            price: 1e4,
            health: 700,
            maxSpeed: 160,
            driver: null,
            passengers: null,
        },
        {
            name: "Sportscar",
            price: 2e4,
            health: 500,
            maxSpeed: 240,
            driver: null,
            passengers: null,
        },
        {
            name: "Luxury Sedan",
            price: 4e4,
            health: 600,
            maxSpeed: 180,
            driver: null,
            passengers: null,
        },
    ],
};
